# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Add support to default build

name: Continuous Integration with Gradle
run-name: ${{ github.actor }} building project.
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - test/**
      - bugfix/**
      - feature/**
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

jobs:
  build:
    name: Build Sabana Backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Spring Gradle Build Action
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clean
        run: ./gradlew clean --scan
      - name: Run tests
        run: ./gradlew test --scan
      - name: Build
        run: ./gradlew build --scan